services:
  flarum:
    image: ghcr.io/viva-la-vita/flarum:development
    build:
      context: ./flarum
    environment:
      URL: http://localhost:${HTTP_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./flarum/php/zzz-flarum.conf:/usr/local/etc/php-fpm.d/zzz-flarum.conf
      - ./flarum/php/flarum.ini:/usr/local/etc/php/conf.d/flarum.ini
      - ./flarum/www/vendor:/var/www/flarum/vendor
      - ./flarum/www/flarum:/var/www/flarum/flarum
      - ./flarum/www/config.php:/var/www/flarum/config.php
      - ./flarum/www/extend.php:/var/www/flarum/extend.php
      - ./flarum/www/site.php:/var/www/flarum/site.php
      - ./flarum/www/composer.json:/var/www/flarum/composer.json
      - ./flarum/www/composer.lock:/var/www/flarum/composer.lock

  nginx:
    image: ghcr.io/viva-la-vita/nginx:development
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
