version: "3"

services:
  flarum:
    image: ghcr.io/viva-la-vita/flarum
    restart: always
    expose:
      - 9000
    environment:
      URL: https://bbs.viva-la-vita.org
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - public:/var/www/flarum/public
      - storage:/var/www/flarum/storage

  nginx:
    image: ghcr.io/viva-la-vita/nginx
    restart: always
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - public:/var/www/flarum/public
      - storage:/var/www/flarum/storage
      - phpmyadmin:/var/www/phpmyadmin
    extra_hosts:
      - "localhost:127.0.0.1"

  mysql:
    image: mysql:8.0
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    restart: always
    environment:
      - PMA_HOST=mysql
    volumes:
      - phpmyadmin:/var/www/html

volumes:
  mysql:
  public:
  storage:
  phpmyadmin:
