version: "3"

services:
  flarum:
    image: ghcr.io/viva-la-vita/flarum
    restart: always
    expose:
      - 9000
    volumes:
      - public:/var/www/flarum/public
      - storage:/var/www/flarum/storage

  nginx:
    image: ghcr.io/viva-la-vita/nginx
    restart: always
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - public:/var/www/flarum/public
      - storage:/var/www/flarum/storage
    extra_hosts:
      - "localhost:127.0.0.1"

  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
  public:
  storage:
